# Generated by Django 2.2.4 on 2019-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(db_index=True, default='user', max_length=150),
        ),
    ]
