# Generated by Django 2.2.4 on 2019-09-23 13:09

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
