# Generated by Django 2.2.4 on 2019-09-30 10:11

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190923_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
